# Generated by Django 3.1.2 on 2020-11-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='temperature',
        ),
    ]
