# Generated by Django 3.1.2 on 2020-11-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_weather_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='area_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='location_key',
            field=models.IntegerField(null=True),
        ),
    ]
