# Generated by Django 3.1.2 on 2020-11-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20201109_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='area_name',
        ),
    ]
