# Generated by Django 3.1.2 on 2020-11-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_remove_weather_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='area_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
