# Generated by Django 3.1.2 on 2020-11-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_weather_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date_time_searched',
            field=models.DateTimeField(null=True),
        ),
    ]
